ligue/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tennis/', include('tennis.urls')),
    path('admin/', admin.site.urls),
]

tennis/urls.py
from django.urls import path

from . import views

app_name = 'tennis'
urlpatterns = [
    path('', views.index, name='index'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('match/<int:pk>/', views.match, name='match'),
    #path('equipe_choice/ligue_choice/<int:id>/match/', views.match, name='match'),
]

tennis/models.py
import datetime
from django.db import models

class Ligue(models.Model) : 
    nom_ligue = models.CharField(max_length=200)
    def __str__(self):
        return self.nom_ligue

class Participant(models.Model):
    nom_participant = models.CharField(max_length=200)
    prenom_participant = models.CharField(max_length=200)
    ligue = models.ForeignKey(Ligue, default = "", on_delete=models.CASCADE)
    def __str__(self):
        return self.nom_participant

class Match(models.Model):
    nom_match = models.CharField(max_length=200)
    date_match = models.DateField(default=datetime.date.today)
    participant = models.ForeignKey(Participant, default = "", on_delete=models.CASCADE)
    score = models.IntegerField()
    def __str__(self):
        return self.nom_match

tennis/forms.py
from django.forms import ModelForm

from .models import Participant, Ligue

class ParticipantForm(ModelForm):

    class Meta:
        model = Participant
        fields = ["nom_participant",
				  "prenom_participant",
                  "ligue"
				]

tennis/views.py
import random
from django.forms import formset_factory
from django.shortcuts import render, redirect

from .models import Participant, Ligue
from .forms import ParticipantForm


def index(request):
    form = ParticipantForm()
    # verification de la methode http
    if request.method == "POST":
        # Instancier le formulaire
        form = ParticipantForm(request.POST)
        # tester le validité du formulaire
        if form.is_valid():
            # enregistrer les données
            form.save()
            # rediriger vers l'index
            return redirect("tennis:index")
    participant_list = Participant.objects.all()
    ligue_list = Ligue.objects.all()
    return render(request, "index.html", {"participant_list": participant_list, "participant_form": form, "ligue_list": ligue_list})

def update(request, pk):
	participant = Participant.objects.get(id = pk)
	form = ParticipantForm(instance=participant)
	if request.method == "POST":
		form = ParticipantForm(request.POST, instance=participant)
		if form.is_valid():
			form.save()
			return redirect("tennis:index")
	return render(request, "update.html", {"edit_participant_form": form})

def delete(request, pk):
	participant = Participant.objects.get(id = pk)
	if request.method == "POST":
		participant.delete()
		return redirect("tennis:index")
	return render(request,"delete.html",{"participant":participant})

def player_pairs(array):
    results = []
    for i in range(0, len(array) - 1):
        for j in range(i+1, len(array)):
            results.append(array[i] + array[j])
    return results

def classement(array):
    score_classer = sorted(array)
    return score_classer

def match(request, pk) :
    list_perso = list(Participant.objects.filter(id = pk).values('nom_participant'))
    list_other = list(Participant.objects.exclude(id =pk).values('nom_participant'))
    match_tab = list(zip(list_other, list_perso))[0]

    participant_final_perso = list(list_perso)
    participant_final_other = list(list_other)
    score = [0, 1, 2, 3, 4, 5, 6, 7]
    scorebis = [7, 6, 5, 4, 3, 2, 1, 0]
    score1 = random.choice(score)
    score2 = random.choice(scorebis)

    return render(request,"match.html", {"match_tab":match_tab, "score1":score1, "score2":score2, "participant_final_perso":participant_final_perso, "participant_final_other":participant_final_other})

       
    

tennis/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>
    	{% block title %}       

        {% endblock title %}
    	Application</title>
</head>
<body>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
      <!-- tooltip -->
  <script src="{% static 'js/script.js'%}"></script>	
</body>
</html>

tennis/templates/delete.html
{% extends 'base.html' %}
{% block title %}
Supprimer un participant | 
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h1 class="text-center">Tennis</h1>
    </div>
    <div class="card-body">
    	<h4>Veux-tu supprimer le participant: <strong>{{participant}}</strong>?</h4>
        <form method="post">
            {% csrf_token %}
            <div class="d-inline-block">
    		<a href="{%url 'tennis:index'%}" class="btn btn-lg btn-secondary"> Annuler</a>
    		</div>
            <div class="d-inline-block">            	
            		<input type="submit" class="btn btn-lg btn-danger" value="Confirmer">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

tennis/templates/index.html
{% extends 'base.html' %}
{% block title %}
Tennis 
{% endblock title %}

{% block content %}

<div class="card">
    <div class="card-header">
        <h1 class="text-center">Participants</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group mb-3">                
                {{participant_form.nom_participant}}  
                {{participant_form.prenom_participant}} 
                
                {{participant_form.ligue}}
                
                           
            </div>
            <button type="submit" class="btn btn-primary btn-lg">AJOUTER</button>
        </form>
        <h4 class="bg-secondary text-light py-2 rounded text-center">Listes des Participants</h4>

        <ul class="list-group">
            {% for participant in participant_list %}
            {% for ligue in ligue_list %}
            <li class="list-group-item list-group-item-action">
                {% if participant.completed == True %}
                <strike>{{participant.nom_participant}} {{participant.prenom_participant }} <span class="badge bg-success text-light">joue à</span> {{ ligue.nom_ligue }}</strike>
                {% else %}
                {{participant.nom_participant}} {{participant.prenom_participant }} <span class="badge bg-success text-light">joue à</span> {{ ligue.nom_ligue }}
                {% endif %}
              <div class="float-end">
                    <a href="{% url 'tennis:match' participant.id %}" class="btn btn-sm btn-success">Choisir</a>

                    <a href="{% url 'tennis:update' participant.id %}" class="btn btn-sm btn-warning">Modifier</a>

                    <a href="{% url 'tennis:delete' participant.id %}" class="btn btn-sm btn-danger">Supprimer</a>
                </div>
            </li>
            {% endfor %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

tennis/templates/match.html
{% extends 'base.html' %}
{% block title %}
Tennis 
{% endblock title %}

{% block content %}

<div class="card">
    <div class="card-header">
        <h1 class="text-center">Match</h1>
    </div>
    <div class="card-body">
        <table class="table table-striped-columns">
            <thead>
                <tr>
                    <th colspan="4" class="text-center">Participants</th>
                </tr>
            </thead>
            <tbody>
                <tr class="table-dark">
                    <td class="text-center">Participants</td>
                    <td class="text-center">Score Participant</td>
                </tr>
                {% for match_list in match_tab %}
                <tr class="table-dark">
                    
                    <td>{{ match_list.nom_participant }}</td>
                    
                    <td class="text-center">{{ score1 }}</td>
                </tr>
               {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>

<div class="card bg-success mt-5 mb-5">
    <div class="card-header">
        <h1 class="text-center">Classement</h1>
    </div>
    <div class="card-body">
        <table class="table table-striped-columns">
            <thead>
                <tr>
                    <th colspan="4" class="text-center">Participants</th>
                </tr>
            </thead>
            <tbody>
                <tr class="table-dark">
                    <td class="text-center">Participants</td>
                    <td class="text-center">Score Participant</td>
                </tr>
                {% for perso_participant in participant_final_perso %}
                <tr class="table-dark">
                    
                        <td>{{ perso_participant.nom_participant }}</td>
                    <td class="text-center">{{ scorefinal }}</td>
                </tr>
                {% endfor %}
                {% for autre_participant in participant_final_other %}
                <tr class="table-dark">
                    
                    <td>{{ autre_participant.nom_participant }}</td>
                    <td class="text-center">{{ scorefinal }}</td>
                </tr>
                
                {% endfor %}
                    
                
               
            </tbody>
        </table>
        
    </div>
</div>
{% endblock content %}

tennis/templates/update.html
{% extends 'base.html' %}
{% block title %}
Modifier un participant | 
{% endblock title %}
{% block content %}
<div class="card">
    <div class="card-header">
        <h1 class="text-center">Tennis</h1>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3">
                <div id="completed" class="input-group-text" data-bs-toggle="tooltip" data-bs-placement="bottom" title="participant inscrit">
                    {{edit_participant_form.completed}}
                </div>
                {{edit_participant_form.nom_participant}}  
                {{edit_participant_form.prenom_participant}} 
                {{ edit_participant_form.ligue }}
                <button type="submit" class="btn btn-lg btn-info">Modifier</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}